### ISSUE TITLE
AOSP 有搞头么

### ISSUE THREAD

**Issue by ResRipper** [dglinux/issues#11]
**AOSP**: 
**https://aosp.tuna.tsinghua.edu.cn/platform/manifest**: 
**164G**:

**Comment by korokor0** [comment]
暂时没有计划在镜像站同步git类的源，您可以通过其他方式同步。

**Comment by ghost** [comment]
git.dgut.edu.cn 搞起来

**Comment by ResRipper** [comment]
然而git那边打不开···
另外现在mirrors全failed了

**Comment by ghost** [comment]
> 然而git那边打不开···

git 其实是 https://git.dglinux.com, 如果能拿到 git.dgut.edu.cn 就爽了
