### ISSUE TITLE
Termux 镜像

### ISSUE THREAD

**Issue by chuangzhu** [dglinux/issues#14]
**名称**: Termux
**上游 URL**: https://termux.net/
**大小**: 41.06 GB

------

Termux 是一个运行在 Android 手机上的终端模拟器和 GNU/Linux 环境，自带 apt 包管理器，对于新手学习 GNU/Linux 可能会很有帮助。

**Comment by POTION4** [comment]
+1

**Comment by korokor0** [comment]
Can be added.

**Comment by 42yeah** [comment]
Done. https://mirrors.dgut.edu.cn/termux/
