### ISSUE TITLE
Add archlinuxcn and manjaro

### ISSUE THREAD

**Issue by ghost** [dglinux/issues#2]
请按模板填写你想添加的镜像信息：

---
**名称**: archlinuxcn
**上游 URL**: Ask repo@archlinuxcn.org
**大小**: 50G

**名称**: Manjaro
**上游 URL**: rsync://ftp.tsukuba.wide.ad.jp/manjaro/
**大小**: 84G

**Comment by g-plane** [comment]
Arch Linux 和 Manjaro 的镜像似乎缺少很多软件包。
