### ISSUE TITLE
请增加linuxmint的镜像源

### ISSUE THREAD

**Issue by dunkeng** [dglinux/issues#21]
请按模板填写你想添加的镜像信息：
https://linuxmint.com/mirrors.php
---
**名称**: Linuxmint镜像
**上游 URL**: rsync-packages.linuxmint.com::packages
**大小**: 25GB

**Comment by korokor0** [comment]
Hi,
We used to have mint mirrors, but decided not to sync them after a vote due to low usage. We are willing to add it again if there is more demand for it.

**Comment by chuangzhu** [comment]
已添加 [linuxmint](https://mirrors.dgut.edu.cn/linuxmint/)。
