### ISSUE TITLE
请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [dglinux/issues#24]
最近开发一个项目 https://github.com/ZenithalHourlyRate/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by MasterKenway** [comment]
欢迎的

**Comment by korokor0** [comment]
Good evening Mogul Z, happy to participate in this project. 

You can get the repo list and their status from  [status.json](https://mirrors.dgut.edu.cn/static/status.json) . If there are changes in the future, we will notify you or submit a pull request if the format is different.

Please let us know if there is anything we could do.

**Comment by ZenithalHourlyRate** [comment]
目前的架构是，加入的镜像自行提供一个结构如同[README](https://github.com/tuna/mirrorz/blob/master/README.md)中的定义的文件，我们不负责解析各个镜像站的原始数据

更多细节都在README中

**Comment by korokor0** [comment]
Done. Thanks!
