### ISSUE TITLE
【镜像请求】Raspberry Pi OS

### ISSUE THREAD

**Issue by tazkeung** [dglinux/issues#25]
请按模板填写你想添加的镜像信息：
http://www.raspbian.org/RaspbianMirrors

---
**名称**: raspbian
**上游 URL**: rsync://archive.raspbian.org/archive/
**大小**: 484.56G

**名称**: raspberrypi
**上游 URL**: rsync://apt-repo.raspberrypi.org/archive/debian/
**大小**: 92.04G

**Comment by korokor0** [comment]
Happy Chinese New Year!
The raspbian image is already available. We are evaluating the raspberry pi mirror. Is there anybody else who wants this mirror?

**Comment by lyekumchew** [comment]
+1

**Comment by tazkeung** [comment]
by the way, looks like the SCAU mirror has down.

**Comment by korokor0** [comment]
> 
> 
> by the way, looks like the SCAU mirror has down.

We don't have the contact information of the SCUA mirror maintainer, but there is a new SUSTech mirror in South China now, which syncs the raspberrypi repo from tuna every 36 hours.

**Comment by chuangzhu** [comment]
+1

**Comment by chuangzhu** [comment]
已添加。
