### ISSUE TITLE
kail的Linux镜像

### ISSUE THREAD

**Issue by RQXGitHub** [dglinux/issues#3]
请按模板填写你想添加的镜像信息：

---
**名称**: 
**上游 URL**: 
**大小**:

**Comment by ghost** [comment]
请按模板填写你想添加的镜像信息：

---
**名称**: Kali
**上游 URL**: rsync://ftp.nluug.nl/kali/
**大小**: 500G

**名称**: Kali Images
**上游 URL**: rsync://ftp.nluug.nl/kali-images/
**大小**: 200G

**Comment by ghost** [comment]
已同步
