### ISSUE TITLE
优麒麟加入东莞理工大学开源软件镜像站申请

### ISSUE THREAD

**Issue by fenshezhuiyi** [dglinux/issues#32]
东莞理工大学开源软件镜像站站长：
您好，我是优麒麟社区Limy（微信号：fenshezhuiyi），随着优麒麟开源操作系统的全球用户不断增多，出现了用户高并发（尤其是新版发布期间）下载镜像负载问题。为了解决负载问题，致力于让爱好者拥有优质下载使用体验的优麒麟团队，除了已提升服务器带宽外，也正积极扩展开源镜像下载渠道。

官方软件仓库网址：archive.ubuntukylin.com
官方镜像库网址：releases.ubuntukylin.com
优麒麟软件仓库和镜像库对外提供同步服务，所需空间共 30.5 G，主要配置如下：
软件仓库同步命令
rsync -av --delete-after archive.ubuntukylin.com::ubuntukylin/ /var/www/ubuntukylin/
所需空间：6.5G
镜像库同步命令
rsync -av --delete-after cdimage.ubuntukylin.com::releases/professional /var/www/ubuntukylin-cdimage/
所需空间：24G

关于优麒麟：
优麒麟开源操作系统自 2013 年创建至今，已累计发行 18 个版本，下载量超过 3600万 次，向开源社区贡献代码 数百万行，被  Linux、Debian、Ubuntu、OpenStack、Ceph 等国际开源社区接收的 patch 超过 7000个，在全球范围内拥有 数十万 活跃用户。

期待站长的回复contact@ubuntukylin.com，谢谢~

**Comment by chuangzhu** [comment]
我们可能没有源中一些软件的再分发权限，如 `wps-office`、`qqmusic`、`baidunetdisk`、`youdao-dict` 等。我们在没有这些软件的再分发许可的前提下，创建镜像将是违反著作权法的行为，希望你们理解。如果可以的话希望你们能与这些合作伙伴沟通，为我们取得这些软件的再分发许可。否则我们可能对软件源中的软件进行评估，仅镜像我们可以再分发的部分。

存在问题的路径：

```
/ubuntukylin/pool/partner/
/ukui/pool/partner/
/ubuntu/pool/main/
```

**Comment by korokor0** [comment]
I'm glad that the first desktop distro I used submitted a mirror request to us.
reference solution :
https://github.com/sjtug/mirror-requests/issues/200#issuecomment-880346727
https://github.com/hitlug/issues/issues/17#issuecomment-723594848

**Comment by chuangzhu** [comment]
初步决定同步的内容：

```
rsync://archive.ubuntukylin.com/ubuntukylin/
```

除 `rsync://archive.ubuntukylin.com/ubuntukylin/pool/partner/`，访问这部分将 302 跳转至 http://archive.ubuntukylin.com/ubuntukylin 下对应的路径。

cdimages 还在评估，因为我基本都要安装一遍才能知道，可能会花费一些时间。

**Comment by fenshezhuiyi** [comment]
感谢站长对优麒麟的支持，关于WPS软件问题，麒麟跟WPS有进行协议的签署。当然我们也有将WPS等若干商业软件去掉重新做的镜像版，同步方式如下：
不带WPS等商业软件的镜像库同步命令：
rsync -av --delete-after cdimage.ubuntukylin.com::releases/basic /本地目录/ubuntukylin-cdimage/ 
所需空间：7.7G
优麒麟软件仓库（源）同步命令：
rsync -av --delete-after archive.ubuntukylin.com::ubuntukylin/ /本地目录/ubuntukylin/ 
所需空间：6.5G

辛苦大家了~

**Comment by chuangzhu** [comment]
已添加 [ubuntukylin](https://mirrors.dgut.edu.cn/ubuntukylin/) [ubuntukylin-cd](https://mirrors.dgut.edu.cn/ubuntukylin-cd/)。
