### ISSUE TITLE
Arch Linux 和 Manjaro 的镜像似乎缺少很多软件包

### ISSUE THREAD

**Issue by ghost** [dglinux/issues#4]
_Originally posted by @g-plane in https://github.com/dglinux/issues/issues/2#issuecomment-433288405_

**Comment by ghost** [comment]
是使用过程中遇到404错误了吗？我自己也有在用 mirrors，并没有遇到什么问题

**Comment by g-plane** [comment]
后来检查是我这边的问题，抱歉打扰了。
