### ISSUE TITLE
有些镜像很久没更新了

### ISSUE THREAD

**Issue by ghost** [dglinux/issues#7]
网站上显示：
Deepin CD | 2018-11-27 10:43
Ubuntu Releases | 2019-01-04 20:09
archlinuxcn | 2019-01-06 13:35
Kali Images | 2018-12-19 11:16
Kali | 2019-01-06 00:09

**Comment by ghost** [comment]
#6

**Comment by ghost** [comment]
还有这个：

Ubuntu | 2019-03-01 17:25

**Comment by korokor0** [comment]
已经正常同步了～

**Comment by ghost** [comment]
还有这个：
Kali Images | 2019-03-04 13:30

**Comment by victoriqueko** [comment]
要不我写个 bot 自动发 issue？
