### ISSUE TITLE
KiCad 镜像

### ISSUE THREAD

**Issue by taotieren** [dglinux/issues#9]
关于开源 EDA 项目的 KiCad PCB 设计软件的镜像。

**Comment by korokor0** [comment]
请按模板填写你想添加的镜像信息：

名称: KiCad PCB
上游 URL: 
大小:

**Comment by taotieren** [comment]
名称: KiCad 夜间版本
上游 URL:https://kicad-downloads.s3.cern.ch/index.html?prefix=windows/nightly/
大小:10G

**Comment by taotieren** [comment]
名称: KiCad Windows 发行版本
上游 URL:https://kicad-downloads.s3.cern.ch/index.html?prefix=windows/stable/
大小:10G

**Comment by taotieren** [comment]
名称: KiCad 下载
上游 URL:https://kicad-downloads.s3.cern.ch/index.html?prefix=
大小:200G

**Comment by taotieren** [comment]
https://github.com/tuna/issues/issues/526#issuecomment-477463940

@AnyMoe

**Comment by AnyMoe** [comment]
I will have a try.

**Comment by korokor0** [comment]
评估s3大小的方法:
```aws --no-sign-request --endpoint-url=https://s3.cern.ch/ s3 ls s3://kicad-downloads/  --recursive  | grep -v -E "(Bucket: |Prefix: |LastWriteTime|^$|--)" | awk 'BEGIN {total=0}{total+=$3}END{print total/1024/1024" MB"}'```
约50.4GB
已同步

**Comment by korokor0** [comment]
暂不同步OS X的镜像

**Comment by taotieren** [comment]
thanks

**Comment by taotieren** [comment]
@AnyMoe KiCad 的同步停了吗？

**Comment by korokor0** [comment]
@taotieren Kicad has been synchronizing. But for technical reasons, we temporarily redirected external access to tuna. We will fix the problem and return the service to normal in the next few days.

**Comment by taotieren** [comment]
Thanks！
